name: CI

on: [push]

jobs:
  test:
    strategy:
      matrix:
        platform: [ubuntu-18.04]
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: '3.8'
    - name: Install tools
      run: |
        python -m pip install --upgrade pip
        pip install gdtoolkit==3.2.7
    - name: Check for problems
      run: make lint
